### ISSUE TITLE
Brakuje informacji jak zbudować projekt

### ISSUE THREAD

**Issue by danielpacak** [wybory2014/Kalkulator1#5]
- Jak zbudować aplikację z wiersza poleceń?
- Jakie IDE?
- Jak uruchamiać testy jednostkowe?
- Integracja z Travis CI?

**Comment by Emzi0767** [comment]
- msbuild Kalkulator1.csproj
- Visual Studio (jest darmowa edycja Express)
- Nie ma
- N/A

**Comment by temp-acc** [comment]
Do zbudowania trzeba dociągnąć referencje:
- BouncyCastle.Crypto: http://www.bouncycastle.org/csharp/ (free)
- DocumentFormat.OpenXml: http://www.microsoft.com/en-us/download/details.aspx?id=30425 (free)
- DocX: http://docx.codeplex.com (free)
- Gnostice.Documents: http://www.gnostice.com/XtremeDocumentStudio_dot_NET.asp?show=downloads (trial 30 dni)
- Ionic.Zip: http://dotnetzip.codeplex.com (free)
- Newtonsoft.Json: http://james.newtonking.com/json (free)
- Zen.Barcode.Core: https://barcoderender.codeplex.com (free)

Do tego dodać WindowsBase z systemu, bo brakuje. Na darmowej VS2013 Express po 3 drobnych poprawkach buduje się bez problemów. Po starcie potrzebny .pem, to już inna bajka.

PS: Testy jednostkowe? Hehehe, dowcipas xD

**Comment by wzin** [comment]
mujborze ;_;

**Comment by danielpacak** [comment]
Dzięki @temp-acc za wyczerpujące wskazówki. Udało mi się skompilować projekt w VS Express.
