### ISSUE TITLE
Sposób na GENEROWANIE KODU DO ODBLOKOWANIA PROTOKOŁU Z OSTRZEŻENIAMI TWARDYMI

### ISSUE THREAD

**Issue by alfikpl** [wybory2014/Kalkulator1#6]
Z kodów aplikacji Kalkulator1 wynika, że algorytm na wygenerowanie tego kodu jest bardzo prosty.

Aby odtworzyć wynik uzyskany w "Instrukcji do systemu syswyb"
(http://zapasdlakbw.home.pl/kalkulator-wyborczy/kalkulator/)
pokazany na ostatniej stronie tego dokumentu należy wpisać: 

echo -n "SMDO01a114112014" | md5sum | cut -c1-10

Ciąg znaków z którego liczony jest skrót nie jest trudny do odgadnięcia. Kod źródłowy w tym względzie jest bardzo klarowny.

Mam w związku z tym nadzieję, że osoby weryfikujące protokoły na wyższym szczeblu nie będą ignorowały "twardych ostrzeżeń".

**Comment by trojkat** [comment]
http://www.tvp.pl/kielce/publicystyka/glos-dnia/wideo/18112014/17703714
